### ISSUE TITLE
How did you obtain those numebers for your policy?

### ISSUE THREAD

**Issue by ashBabu** [ZhiqingXiao/OpenAIGymSolution#1]
Hello, 
Could you please explain how did you arrive at the various numerical values used in this policy?
``` min(-0.09 (position + 0.25)² + 0.03, 0.3 (position + 0.9)⁴ - 0.008) < velocity < -0.07 (position + 0.38)² + 0.07  ```

**Comment by ZhiqingXiao** [comment]
These numbers can be found by varied non-gradient optimization algorithms, such as evolution strategy.
